config/routes.rb
Ghog724::Application.routes.draw do

  resources :albums
  resources :users
  resources :photos

  root :to => 'albums#index'
end

app/models/album.rb
class Album < ActiveRecord::Base

  has_many :photos
  belongs_to :user

  attr_accessible :title, :user_id

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
  belongs_to :album
  belongs_to :user
  
  attr_accessible :album_id, :title

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :albums
  has_many :photos
  
  attr_accessible :name, :password

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
  end
  
  def new
    @album = Album.new
  end
  
  def create
    @album = Album.new(params[:album])
    @album.save
    redirect_to @album
  end
  
  def show
    @album = Album.find(params[:id])
  end
  
  def edit
    @album = Album.find(params[:id])
  end
  
  def update
    @album = Album.find(params[:id])
    @album.update_attributes(params[:album])
    redirect_to @album
  end
  
  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to '/'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end
  
  def show
    @photo = Photo.find(params[:id])
  end
  
  def create
    @photo = Photo.new(params[:photo])
    if @photo.save
      redirect_to @photo.album, notice: 'photo was uploaded'
    else
      render action: 'new'
    end
  end
  
  def edit
    @photo = Photo.find(params[:id])
  end
  
  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(params[:photo])
      redirect_to @photo, notice: 'Photo has been updated'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, notice: 'new user succesful!'
    else
      render action: 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'Successfully edited'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
  
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/albums/edit.html.erb
<h2>Edit Album</h2>
<%= render 'form' %>
<%= link_to 'back', '/' %>

app/views/albums/index.html.erb
<h2>Albums</h2>

<table>
  <tr>
    <th>Album Title</th>
    <th>User</th>
    <th>Actions</th>
  </tr>
  <% @albums.each do |a| %>
  <tr>
    <td><%= link_to a.title, a %></td>
    <td><%= link_to a.user.name, a.user %></td>
    <td><%= link_to 'Edit', edit_album_path(a) %></td>
    <td><%= link_to 'Delete', a, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
  <% end %>
</table>
<p><%= link_to 'New Album', new_album_path %> | <%= link_to 'Users', users_path %> | <%= link_to 'Photos', photos_path %></p>

app/views/albums/new.html.erb
<h2>New Album</h2>
<%= render 'form' %>
<%= link_to 'back', '/' %>

app/views/albums/show.html.erb
<h2><%= @album.title %></h2>
<h3>Uploaded by: <%= @album.user_id %></h3>

<ul>
  <% @album.photos.each do |p| %>
  <li><%= link_to p.title, p %></li>
  <% end %>
</ul>
<%= link_to 'Add Photo', new_photo_path(@photo) %> |
<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', '/' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ghog724</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1><a href="/">Groundhog 7-24</a></h1>
<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :album_id %><br />
    <%= f.number_field :album_id %>
  </div>


  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h2>Edit Photo</h2>
<%= render 'form' %>
<%= link_to 'Back', @photo %>

app/views/photos/index.html.erb
<h2>Photos</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Album Name</th>
    <th>User</th>
    <th>Delete</th>
  </tr>
  <% @photos.each do |p| %>
  <tr>
    <td><%= link_to p.title, p %></td>
    <td><%= link_to p.album.title, p.album %></td>
    <td><%= link_to p.album.user.name, p.user %></td>
    <td><%= link_to 'x', p, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
  <% end %>  
</table>

<p><%= link_to 'New Photo', new_photo_path %> | <%= link_to 'Albums', albums_path %> | <%= link_to 'Users', users_path %></p>

app/views/photos/new.html.erb
<h2>Upload Photo</h2>
<%= render 'form' %>
<%= link_to 'Back', @photo %>

app/views/photos/show.html.erb
<h2>Photo</h2>

<p><%= @photo.title %> from the album: <%= @photo.album.title %></p>
<p>Uploaded by: <%= @photo.album.user.name %></p>

<%= link_to 'Edit Photo', edit_photo_path(@photo) %> |
<%= link_to 'Delete Photo', @photo, confirm: 'Are you sure?', method: :delete %> |
<%= link_to 'View Albums', albums_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/edit.html.erb
<h2>Edit: <%= @user.name %></h2>
<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2>Users</h2>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th>Delete?</th>
  </tr>
  <% @users.each do |u| %>
    <tr>
      <td><%= link_to u.name, u %></td>
      <td><%= u.password %></td>
      <td><%= link_to 'x', u, confirm: 'For sure?', method: :delete  %></td>
    </tr>
  <% end %>    
</table>

<p><%= link_to 'New User', new_user_path %> | <%= link_to 'Albums', albums_path %> | <%= link_to 'Photos', photos_path %></p>

app/views/users/new.html.erb
<h2>New User</h2>
<%= render 'form' %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<p>Password: <%= @user.password %></p>

<ul>
  <% @user.albums.each do |a| %>
  <li><%= link_to a.title, a %></li>
  <% end %>
</ul>
  
<%= link_to 'New Album', new_album_path(@album) %> |
<%= link_to 'Edit Profile', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>